### ISSUE TITLE
redo already_loaded using __spec__.origin

### ISSUE THREAD

**Issue by reynoldsnlp** [reynoldsnlp/pip_inside#3]
from @ncoghlan [here](https://github.com/pypa/pip/issues/5069#issue-305765776)

> after the installation operation completes, read the RECORD entries for any just installed modules, and compare them to \_\_spec\_\_.origin and importlib.util.source_from_cache(\_\_spec\_\_.origin\_\_) for all of the modules in sys.modules.values() and emit a warning to stderr suggesting a Python session restart if any of the just installed files is already loaded in the module cache.

**Comment by ncoghlan** [comment]
Right, as the current implementation runs into the problem that having the PyPI distribution package name be the same as the top level Python import package is only a common *convention*, rather than a hard requirement, so while there a lot of cases that it will correctly warn about, there are also quite a few that it will miss (e.g. while you install `Pillow`, you actually import from `PIL`, since `Pillow` was originally designed to serve as a drop-in replacement for an older project using the latter name). 

When reworking this, there's also a smaller tweak that would be appropriate, which is to print the related warning messages to `stderr` rather than `stdout` (there's relatively few cases where that will make a practical difference, but `stderr` is the more suitable target stream)

**Comment by reynoldsnlp** [comment]
@ncoghlan What do you mean "read the RECORD entries for any just installed modules"?

Also, `source_from_cache` isn't as straightforward to use as I was hoping. I ran into the following error, which I assume has to do with PEP 3147 or 488: https://docs.python.org/3/library/importlib.html#importlib.util.source_from_cache. Help?

```python
>>> sys.modules['pip']
<module 'pip' from '/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/__init__.py'>
>>> sys.modules['pip'].__spec__.origin
'/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/__init__.py'
>>> source_from_cache(sys.modules['pip'].__spec__.origin)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap_external>", line 324, in source_from_cache
ValueError: __pycache__ not bottom-level directory in '/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/__init__.py'
```

**Comment by ncoghlan** [comment]
The `ValueError` is reporting that the path you submitted isn't a valid `__pycache__` entry, so the function can't infer an original source location from it. To see what the function is expecting as input, run the path you have there through `importlib.util.cache_from_source`:

```
>>> from importlib.util import cache_from_source, source_from_cache
>>> pip_path = sys.modules["pip"].__spec__.origin
>>> pip_path
'/usr/lib/python3.7/site-packages/pip/__init__.py'
>>> cache_from_source(pip_path)
'/usr/lib/python3.7/site-packages/pip/__pycache__/__init__.cpython-37.pyc'
>>> source_from_cache(cache_from_source(pip_path))
'/usr/lib/python3.7/site-packages/pip/__init__.py'
```

I think the actual error is in my initial notes though: I forgot that the source file loader sets `origin` as the source location (even if the module itself gets initialised from the cached bytecode file), so you should be able to just use `__spec__.origin` directly and not need to worry about converting it at all.

(There's a separate optional `__spec__.cached` attribute to let loaders report the case where they've loaded from the cache directory instead of directly from the origin file)

**Comment by ncoghlan** [comment]
For "reading the `RECORD` file", I'm referring to the installation database in PEP 376, where `pip` (and other compliant installers) make a full record of the files installed for each package: https://www.python.org/dev/peps/pep-0376/#record

And unlike `sys.modules`, that installation database uses *distribution* package names (the ones that get passed to `pip install` on the command line) rather than the import package names, so as a first attempt, the CLI wrapper can use the positional arguments to get the list of names that it needs to query. (Ideally it would also check all the dependencies that get upgraded, but that will be a bit tricky when implementing this as a CLI wrapper, so I think it would make sense to defer checking dependency reloading until after pip is providing this functionality natively)

You don't need to read the `RECORD` file directly, though: `pip` already includes a vendored copy of `distlib` (as `pip._vendor.distlib`), so for `pip_inside`, you can just depend on `distlib` and let it do the heavy lifting via https://distlib.readthedocs.io/en/latest/reference.html#InstalledDistribution.list_installed_files:

```
>>> requested_dist_packages = ["pip", "wheel"] # just an example
>>> import distlib, os.path
>>> dist_path = distlib.database.DistributionPath()
>>> dist_info = [dist_path.get_distribution(dist_name) for dist_name in requested_dist_packages]
>>> file_paths = set(os.path.join(os.path.dirname(project.path), path) for project in dist_info for path, __, __ in project.list_installed_files())
>>> import sys, pip
>>> sys.modules["pip"].__spec__.origin in file_paths
True

**Comment by reynoldsnlp** [comment]
https://github.com/reynoldsnlp/pip_inside/tree/%233-origin

@ncoghlan `dist_path` is behaving strangely for me. Works for some and doesn't work for others (It does work for both `pip` and `wheel`)

```python
>>> from pip._vendor.distlib.database import DistributionPath
>>> dist_path = DistributionPath()
>>> for d in Path('/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages').glob('*'):
...   print(dist_path.get_distribution(d.stem), d.stem, sep='\t')
...
None	appdirs-1.4.3
None	olefile
None	decorator-4.3.0-py3.6
boto 2.48.0	boto
None	mesa
mistune 0.8.3	mistune
None	Pillow-4.3.0
Flask 0.12.2	flask
selenium 3.7.0	selenium
None	python_dateutil-2.6.1
None	pysptk-0.1.11
None	simplegeneric
tinysegmenter 0.3	tinysegmenter
appnope 0.1.0	appnope
packaging 16.8	packaging
None	simplegeneric-0.8.1-py3.6.egg-info
None	testpath-0.3.1
None	ply
None	tornado-5.1.1
None	thinc-6.10.2
thinc 6.10.2	thinc
None	tqdm-4.19.8
None	mathutils.cpython-36m-darwin
None	chardet-3.0.4
None	gensim-3.1.0
None	msgpack
None	networkx
None	praat_parselmouth-0.3.2
wcwidth 0.1.7	wcwidth
None	python_dateutil-2.7.3-py3.6
toolz 0.9.0	toolz
None	markupsafe
None	jupyter_core
None	termcolor
None	oauthlib-2.0.6-py3.6
None	widgetsnbextension
None	jupyter_client-5.2.1
py 1.5.2	py
None	Markdown-2.6.11
chardet 3.0.4	chardet
None	appnope-0.1.0-py3.6
webencodings 0.5.1	webencodings
None	requests_oauthlib
None	backcall
None	DAWG_Python-0.7.2
None	boto-2.48.0
None	qtconsole-4.4.1
None	termcolor-1.1.0-py3.6
nbformat 4.4.0	nbformat
None	entrypoints-0.2.3
None	mysql_connector-2.1.6
None	easy_install
None	webencodings-0.5.1
None	pandocfilters-1.4.2
None	tkSnack-2.2.9-py3.6
s3transfer 0.1.12	s3transfer
None	bleach-1.5.0
None	wcwidth-0.1.7-py3.6
None	murmurhash
None	scikit_learn-0.19.1
None	oauthlib
None	traitlets-4.3.2-py3.6
bleach 1.5.0	bleach
Pygments 2.2.0	pygments
None	hanziconv
Mako 1.0.7	mako
None	ipykernel_launcher.py
None	tornado-5.1.1-py3.6
None	tensorflow-1.6.0
None	_regex.cpython-36m-darwin
None	cycler-0.10.0
None	pyzmq-17.1.2
None	decorator-4.1.2
None	pytest-3.3.1
None	matplotlib-2.1.0-py3.6-nspkg
None	pickleshare.py
None	pylab
None	wcwidth-0.1.7
None	ipywidgets
docutils 0.14	docutils
None	docopt
None	grpc
flake8 3.5.0	flake8
None	jupyter_console-5.2.0
None	docx2txt
None	preshed
None	python_oauth2-1.1.0
None	pamela-0.3.0
None	astor-0.6.2
None	cymem
None	dawg_python
Jinja2 2.9.6	jinja2
None	pluggy-0.6.0-py3.6
None	itsdangerous
None	ujson.cpython-36m-darwin
ipython 6.2.1	IPython
XlsxWriter 1.0.2	xlsxwriter
None	numpy-1.14.2
None	ujson-1.35-py3.6
None	jupyter_client
None	nltk
None	ptyprocess-0.6.0-py3.6
None	s3transfer-0.1.12
argcomplete 1.8.2	argcomplete
None	MarkupSafe-1.0-py3.6
decorator 4.1.2	decorator
None	itsdangerous-0.24-py3.6
Markdown 2.6.11	markdown
None	tinysegmenter-0.3
None	idna-2.6
None	google
None	lxml-4.1.1
None	selenium-3.7.0
None	pdfminer3k-1.3.1-py3.6
None	boto3-1.4.8
None	dill-0.2.7.1-py3.6
None	msgpack_numpy-0.4.1
None	parso-0.3.1-py3.6
None	fa2
None	ptyprocess-0.5.2
None	toolz-0.9.0
None	gast
elsapy 0.4.6	elsapy
None	pickleshare-0.7.5-py3.6
None	plac_core
None	ipykernel_launcher
None	readline
None	Werkzeug-0.12.2
None	OleFileIO_PL
jedi 0.11.0	jedi
pysptk 0.1.11	pysptk
None	pymorphy2_dicts-2.4.393442.3710985
None	jupyter_client-5.2.4-py3.6
Send2Trash 1.5.0	send2trash
None	absl
None	ipython_genutils
None	ftfy-4.4.3-py3.6
None	space_diff-0.0.2
None	pygame-1.9.3
None	en_core_web_sm-2.0.0-py3.6
None	docopt-0.6.2-py3.6
None	oauth2
tldextract 2.2.0	tldextract
None	jupyter_core-4.4.0-py3.6
None	mccabe-0.6.1
None	docx2txt-0.6-py3.6
idna 2.6	idna
Werkzeug 0.12.2	werkzeug
wheel 0.30.0	wheel
None	bs4
click 6.7	click
None	backcall-0.1.0-py3.6
None	protobuf-3.5.2
pickleshare 0.7.4	pickleshare
None	test_regex
None	cytoolz
None	pyparsing-2.2.0
None	decorator.py
None	scipy-1.0.0
mccabe 0.6.1	mccabe
None	jieba
None	smart_open
None	pytz-2017.3
None	elsapy-0.4.6
None	Mesa-0.8.2-py3.6
None	jedi-0.11.0
None	mpl_toolkits
None	argcomplete-1.8.2
pytz 2017.3	pytz
None	newspaper
None	mathutils-2.79.1
None	docutils-0.14
tweepy 3.5.0	tweepy
None	__pycache__
None	tweepy-3.5.0
None	docs
SQLAlchemy 1.2.15	sqlalchemy
None	readline_path
None	nbconvert-5.3.1
pygame 1.9.3	pygame
None	pickleshare-0.7.4
None	smart_open-1.5.5-py3.6
None	wrapt
None	speech_recognition
None	ipykernel-4.7.0
numpy 1.14.2	numpy
pyreaper 0.0.5	pyreaper
None	simplediff-1.0-py3.6
None	jupyterhub
None	async_generator
astor 0.6.2	astor
botocore 1.8.10	botocore
gensim 3.1.0	gensim
None	PIL
requests 2.18.4	requests
None	ipython_genutils-0.2.0-py3.6
None	ipython-6.5.0-py3.6
None	pymorphy2_dicts
None	requests_oauthlib-0.8.0
None	testpath
None	beautifulsoup4-4.5.3
appdirs 1.4.3	appdirs
None	Mako-1.0.7
None	gast-0.2.0-py3.6
html5lib 0.9999999	html5lib
None	jieba3k-0.35.1
None	plac_ext
None	pycodestyle-2.3.1
pip 9.0.3	pip
None	bz2file-0.98-py3.6
tornado 5.1.1	tornado
None	msgpack_numpy
None	Pygments-2.2.0
None	bz2file
None	sklearn
None	plac-0.9.6
None	pdfminer
None	python_pptx-0.6.5-py3.6
None	jupyterhub-0.9.4
None	async_generator-1.10
None	pip-18.1
None	hanziconv-0.3.2-py3.6
certifi 2018.1.18	certifi
None	prompt_toolkit
pandocfilters 1.4.2	pandocfilters
None	_tkinter.cpython-36m-darwin
None	cssselect-1.0.3
None	ipython_genutils-0.2.0
None	ipykernel-5.0.0-py3.6
None	widgetsnbextension-3.4.0
None	parso-0.1.0
None	attr
pexpect 4.2.1	pexpect
None	certifi-2018.1.18
xlrd 1.0.0	xlrd
None	tensorboard-1.6.0
None	pexpect-4.2.1
jsonschema 2.6.0	jsonschema
None	jieba-0.39-py3.6
None	tkinter-0.0.0-py3.6
pytest 3.3.1	pytest
None	botocore-1.8.10
None	tlz
None	jupyter_core-4.4.0
None	click-6.7
None	pandas-0.22.0
None	jupyter_console
None	pptx
None	murmurhash-0.28.0-py3.6
None	requests_file-1.4.3
tqdm 4.19.8	tqdm
None	ipython-6.2.1
None	simplediff
pycodestyle 2.3.1	pycodestyle
plac 0.9.6	plac
None	readline
None	olefile-0.44-py3.6
None	Pygments-2.3.1-py3.6
None	examples
None	nltk-3.2.5-py3.6
None	jupyter-1.0.0
None	pymorphy2-0.8
None	mysql
None	entrypoints
tensorflow 1.6.0	tensorflow
None	fa2-0.2-py3.6
None	ply-3.10-py3.6
None	pyflakes-1.6.0
None	attrs-17.3.0
None	ptyprocess
six 1.11.0	six
tensorboard 1.6.0	tensorboard
None	en_core_web_sm
None	SQLAlchemy-1.2.15
None	mysql_latin1_codec-2.0
None	jedi-0.13.2-py3.6
None	absl_py-0.1.11-py3.6
None	py-1.5.2
cycler 0.10.0	cycler
None	jupyter.py
None	pluggy
None	preshed-1.0.0-py3.6
None	setuptools-40.6.2-py3.6
None	mistune-0.8.3
None	six-1.11.0
None	grpcio-1.10.0
matplotlib 2.1.0	matplotlib
None	regex-2017.4.5-py3.6
None	yaml
None	prometheus_client
None	qtconsole
None	README
None	ebooklib
None	matplotlib-2.1.0
jmespath 0.9.3	jmespath
None	pathlib-1.0.1-py3.6
None	newspaper3k-0.2.8
None	msgpack_python-0.5.4
None	tldextract-2.2.0
alembic 1.0.5	alembic
None	wheel-0.30.0
urllib3 1.22	urllib3
nbconvert 5.3.1	nbconvert
None	xlrd-1.0.0
None	feedfinder2-0.0.4
None	appnope-0.1.0
feedfinder2 0.0.4	feedfinder2
None	setuputils
None	requests_file
None	urllib3-1.22
None	editor
None	html5lib-0.9999999
feedparser 5.2.1	feedparser
None	networkx-2.0-py3.6
None	feedparser-5.2.1
None	ftfy
None	prompt_toolkit-1.0.15-py3.6
None	nbformat-4.4.0
None	external
pymorphy2 0.8	pymorphy2
None	pyzmq-17.1.2-py3.6
None	setuptools
None	pkg_resources
notebook 5.7.4	notebook
None	simplegeneric.py
spacy 2.0.10	spacy
None	alembic-1.0.5
None	python_editor-1.0.3
None	terminado
None	simplegeneric-0.8.1-py3.6
None	Send2Trash-1.5.0
parso 0.1.0	parso
None	PyYAML-3.12-py3.6
None	EbookLib-0.15-py3.6
None	plac_tk
None	requests-2.18.4
None	pathlib
None	parselmouth.cpython-36m-darwin
None	cymem-1.31.2-py3.6
None	dulwich-0.18.6
None	prompt_toolkit-1.0.15
traitlets 4.3.2	traitlets
None	notebook-5.7.4
None	cytoolz-0.8.2-py3.6
lxml 4.1.1	lxml
None	packaging-16.8
scipy 1.0.0	scipy
None	sklearn-0.0-py3.6
None	zmq
None	pyreaper-0.0.5
None	dill
None	XlsxWriter-1.0.2
None	regex
None	jsonschema-2.6.0
None	pip-9.0.3
None	pip-18.1-py3.6
None	prometheus_client-0.3.1
None	Jinja2-2.9.6
None	tkSnack
None	jmespath-0.9.3
None	Flask-0.12.2
ipykernel 4.7.0	ipykernel
pyparsing 2.2.0	pyparsing
None	six.py
pandas 0.22.0	pandas
None	dateutil
None	flake8-3.5.0
None	traitlets-4.3.2
None	_pytest
None	six-1.12.0-py3.6
None	protobuf-3.5.2-py3.6-nspkg
None	pexpect-4.6.0-py3.6
None	space-diff
None	ipywidgets-7.4.0
pamela 0.3.0	pamela
None	terminado-0.8.1
None	wrapt-1.10.11-py3.6
None	spacy-2.0.10
pyflakes 1.6.0	pyflakes
None	_regex_core
jupyter 1.0.0	jupyter
cssselect 1.0.3	cssselect
boto3 1.4.8	boto3
dulwich 0.18.6	dulwich
None	mysql_latin1_codec
None	SpeechRecognition-3.6.3

**Comment by ncoghlan** [comment]
One big item I noticed after some local experimentation is that `distlib.DistributionPath` needs to have `include_egg=True` passed in for it to correctly pick up projects that are still emitting the old pre-PEP-376 `egg-info` format - by default it will only pick up the newer dist-info format defined in that PEP.

However, there are also a couple of challenges that apply specifically to your current attempted behaviour check:

* the site-packages directory include actual `*.py` import modules in addition to `*.dist-info` and `*.egg-info` metadata directories and files
* `.` is a legal character in `dist-info` directory names, so a simple `stem` call won't reliably extract the distribution package name, you need to instead look for the first `-` character and use everything before that

Applying those three changes gives:

```
>>> import pathlib
>>> import distlib.database
>>> dist_path = distlib.database.DistributionPath(include_egg=True)
>>> for distpkg in pathlib.Path("/usr/lib/python3.7/site-packages/").glob("*.*-info"):
...     distname = distpkg.name.partition('-')[0]
...     print(f"{distname:20}{dist_path.get_distribution(distname)}")
... 
SSSDConfig          SSSDConfig 2.0.0
pydbus              pydbus 0.6.0
sepolicy            sepolicy 1.1
python_meh          None
pystray             pystray 0.14.3
requests_file       None
pip                 pip 18.1
slip                slip 0.6.4
decorator           decorator 4.3.0
simpleline          simpleline 1.4
python_xlib         None
distro              distro 1.3.0
docutils            docutils 0.14
IPy                 IPy 0.81
blivet              blivet 3.1.2
isc                 isc 2.0
tox                 tox 3.4.0
productmd           productmd 1.18
virtualenv          virtualenv 16.0.0
sos                 sos 3.6
PyGObject           PyGObject 3.30.4
pyinotify           pyinotify 0.9.6
olefile             olefile 0.46
pluggy              pluggy 0.6.0
idna                idna 2.7
asn1crypto          asn1crypto 0.24.0
langtable           langtable 0.0.40
ply                 ply 3.9
fros                fros 1.1
requests            requests 2.20.0
blivet_gui          None
PySocks             PySocks 1.6.8
pycparser           pycparser 2.14
sh                  sh 1.12.14
chardet             chardet 3.0.4
ntplib              ntplib 0.3.3
slip.dbus           slip.dbus 0.6.4
pid                 pid 2.1.1
humanize            humanize 0.5.1
pytz                pytz 2018.5
pyOpenSSL           pyOpenSSL 18.0.0
six                 six 1.11.0
requests_ftp        None
toml                toml 0.10.0
urllib3             urllib3 1.24.1
cupshelpers         cupshelpers 1.0
pyparsing           pyparsing 2.2.0
ordered_set         None
pykickstart         pykickstart 3.16
pyudev              pyudev 0.21.0
initial_setup       None
python_augeas       None
setuptools          setuptools 40.6.3
py                  py 1.5.4
iniparse            iniparse 0.4
```

**Comment by ncoghlan** [comment]
That initial list still had a few `None` response in it, and it turned out those where due to the name on disk having `_` where the original name has `-` (to abide by the naming restriction imposed by the fact that metadata directory naming scheme uses `-` as a field separator). Reversing that transformation allows `distlib` to find all the entries in that directory on my system:

```
>>> import pathlib
>>> import distlib.database
>>> dist_path = distlib.database.DistributionPath(include_egg=True)
>>> for distpkg in sorted(pathlib.Path("/usr/lib/python3.7/site-packages/").glob("*.*-info")):
...     distname = distpkg.name.partition('-')[0].replace('_', '-')
...     print(f"{distname:20}{dist_path.get_distribution(distname)}")
... 
IPy                 IPy 0.81
PyGObject           PyGObject 3.30.4
PySocks             PySocks 1.6.8
SSSDConfig          SSSDConfig 2.0.0
asn1crypto          asn1crypto 0.24.0
blivet              blivet 3.1.2
blivet-gui          blivet-gui 2.1.10
chardet             chardet 3.0.4
cupshelpers         cupshelpers 1.0
decorator           decorator 4.3.0
distro              distro 1.3.0
docutils            docutils 0.14
fros                fros 1.1
humanize            humanize 0.5.1
idna                idna 2.7
iniparse            iniparse 0.4
initial-setup       initial-setup 0.3.62
isc                 isc 2.0
langtable           langtable 0.0.40
ntplib              ntplib 0.3.3
olefile             olefile 0.46
ordered-set         ordered-set 2.0.2
pid                 pid 2.1.1
pip                 pip 18.1
pluggy              pluggy 0.6.0
ply                 ply 3.9
productmd           productmd 1.18
py                  py 1.5.4
pyOpenSSL           pyOpenSSL 18.0.0
pycparser           pycparser 2.14
pydbus              pydbus 0.6.0
pyinotify           pyinotify 0.9.6
pykickstart         pykickstart 3.16
pyparsing           pyparsing 2.2.0
pystray             pystray 0.14.3
python-augeas       python-augeas 0.5.0
python-meh          python-meh 0.47
python-xlib         python-xlib 0.23
pytz                pytz 2018.5
pyudev              pyudev 0.21.0
requests            requests 2.20.0
requests-file       requests-file 1.4.3
requests-ftp        requests-ftp 0.3.1
sepolicy            sepolicy 1.1
setuptools          setuptools 40.6.3
sh                  sh 1.12.14
simpleline          simpleline 1.4
six                 six 1.11.0
slip                slip 0.6.4
slip.dbus           slip.dbus 0.6.4
sos                 sos 3.6
toml                toml 0.10.0
tox                 tox 3.4.0
urllib3             urllib3 1.24.1
virtualenv          virtualenv 16.0.0
```

**Comment by reynoldsnlp** [comment]
@ncoghlan, using `include_egg=True` breaks `DistributionPath` for me. Could it be connected to the fact that I'm using `pip`'s bundled version of `distlib`?

```
>>> from pip._vendor.distlib.database import DistributionPath
>>> dp = DistributionPath()
>>> dp.get_distribution('pip')
<InstalledDistribution 'pip' 9.0.3 at '/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip-9.0.3.dist-info'>
```

... however ...

```
>>> dp = DistributionPath(include_egg=True)
>>> dp.get_distribution('pip')
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/distlib/metadata.py", line 727, in __init__
    self._data = json.loads(data)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/distlib/database.py", line 237, in get_distribution
    self._generate_cache()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/distlib/database.py", line 164, in _generate_cache
    for dist in self._yield_distributions():
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/distlib/database.py", line 154, in _yield_distributions
    yield old_dist_class(r.path, self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/distlib/database.py", line 875, in __init__
    metadata = self._get_metadata(path)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/distlib/database.py", line 955, in _get_metadata
    metadata = Metadata(path=path, scheme='legacy')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/distlib/metadata.py", line 737, in __init__
    scheme=scheme)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/distlib/metadata.py", line 281, in __init__
    self.read_file(fileobj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/distlib/metadata.py", line 381, in read_file
    self.set_metadata_version()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/distlib/metadata.py", line 287, in set_metadata_version
    self._fields['Metadata-Version'] = _best_version(self._fields)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/distlib/metadata.py", line 165, in _best_version
    raise MetadataConflictError('Unknown metadata set')
pip._vendor.distlib.metadata.MetadataConflictError: Unknown metadata set
```

**Comment by ncoghlan** [comment]
I don't what might cause that.

@vsajip, @reynoldsnlp is attempting to use `distlib` to work out what modules are installed and read their `RECORD` files so we can use that to print a "this module is already loaded, you may need to restart Python" warning, but he's having trouble getting it to give consistent answers on Mac OS X.

Are the above issues a sign that there's a package with bad metadata on the system, or something else?

**Comment by vsajip** [comment]
>  a sign that there's a package with bad metadata on the system

Possibly - it seems to indicate a file that's invalid at the JSON level rather than the level of any schema. It may be that it's trying to interpret a non-JSON file as JSON. Perhaps if @reynoldsnlp could find what the file actually being read contains, we might be able to make progress.

It might also be worth trying the repo version of `distlib` rather than the last released version (0.2.8). I assume that's the standalone version used above.

**Comment by ncoghlan** [comment]
@reynoldsnlp It may be worth trying to catch the exception with a debugger to see exactly which file `distlib` is looking at when it fails. For example, with [pdb.pm](https://docs.python.org/3/library/pdb.html#pdb.post_mortem):

    try:
        dp.get_distribution('pip')
    except:
        import pdb; pdb.pm()

**Comment by reynoldsnlp** [comment]
I don't have much time to work on this this morning, but I thought I would at least post output of the debugger. It doesn't give any more information than the Tracebacks above.

using the bundled `distlib` with `include_egg`:
```
>>> from pip._vendor.distlib.database import DistributionPath
>>> dp = DistributionPath(include_egg=True)
>>> try:
...     dp.get_distribution('pip')
... except:
...     import pdb; pdb.pm()
...
> /opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/distlib/metadata.py(165)_best_version()
-> raise MetadataConflictError('Unknown metadata set')
>>>
```

...and using the standalone `distlib`:
```
>>> from distlib.database import DistributionPath
>>> dp = DistributionPath()
>>> try:
...     dp.get_distribution('pip')
... except:
...     import pdb; pdb.pm()
...
> /Users/myuser/Library/Python/3.6/lib/python/site-packages/distlib/version.py(116)__init__()
-> '%r constraints' % op)
```
